/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ec.edu.ups.vista;

import ec.edu.ups.controlador.ControladorCliente;
import ec.edu.ups.controlador.ControladorVehiculo;
import ec.edu.ups.modelo.Cliente;
import ec.edu.ups.modelo.Vehiculo;
import java.text.ParseException;
import javax.swing.JButton;
import javax.swing.JFormattedTextField;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JTextField;

/**
 *
 * @author paul_
 */
public class VentanaVehiculo extends javax.swing.JInternalFrame {

    private ControladorVehiculo controladorVehiculo;
    private ControladorCliente controladorCliente;
    private VentanaCliente ventanaCliente;
    private VentanaPrincipal ventanaPrincipal;

    public VentanaVehiculo(ControladorVehiculo controladorVehiculo, ControladorCliente controladorCliente, VentanaPrincipal ventanaPrincipal) throws ParseException {
        initComponents();

        this.controladorCliente = controladorCliente;
        this.controladorVehiculo = controladorVehiculo;
        this.ventanaPrincipal = ventanaPrincipal;
        ventanaCliente = new VentanaCliente(this.controladorCliente, this.ventanaPrincipal, this);

        txtPlaca.setFormatterFactory(
                new javax.swing.text.DefaultFormatterFactory(
                        new javax.swing.text.MaskFormatter("***-####")
                ));
        txtCedula.setEnabled(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelVehiculo = new javax.swing.JPanel();
        lblPlaca = new javax.swing.JLabel();
        lblMarca = new javax.swing.JLabel();
        lblModelo = new javax.swing.JLabel();
        txtMarca = new javax.swing.JTextField();
        txtModelo = new javax.swing.JTextField();
        btnCrearVehiculo = new javax.swing.JButton();
        txtPlaca = new javax.swing.JFormattedTextField();
        lblCEDULA = new javax.swing.JLabel();
        txtCedula = new javax.swing.JTextField();

        PanelVehiculo.setBackground(new java.awt.Color(255, 255, 255));
        PanelVehiculo.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Datos del Vehiculo", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Tahoma", 0, 18))); // NOI18N

        lblPlaca.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lblPlaca.setText("Placa del vehiculo:");

        lblMarca.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lblMarca.setText("Marca del vehiculo:");

        lblModelo.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lblModelo.setText("Modelo del vehiculo:");

        btnCrearVehiculo.setBackground(new java.awt.Color(204, 255, 255));
        btnCrearVehiculo.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        btnCrearVehiculo.setText("CREAR");
        btnCrearVehiculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrearVehiculoActionPerformed(evt);
            }
        });

        lblCEDULA.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lblCEDULA.setText("Cedula:");

        txtCedula.setEnabled(false);

        javax.swing.GroupLayout PanelVehiculoLayout = new javax.swing.GroupLayout(PanelVehiculo);
        PanelVehiculo.setLayout(PanelVehiculoLayout);
        PanelVehiculoLayout.setHorizontalGroup(
            PanelVehiculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelVehiculoLayout.createSequentialGroup()
                .addGroup(PanelVehiculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelVehiculoLayout.createSequentialGroup()
                        .addGroup(PanelVehiculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PanelVehiculoLayout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(PanelVehiculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblPlaca)
                                    .addComponent(lblCEDULA))
                                .addGap(44, 44, 44))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelVehiculoLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(PanelVehiculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblModelo)
                                    .addComponent(lblMarca))
                                .addGap(34, 34, 34)))
                        .addGroup(PanelVehiculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelVehiculoLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(txtModelo, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(PanelVehiculoLayout.createSequentialGroup()
                                .addGap(16, 16, 16)
                                .addGroup(PanelVehiculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtCedula, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(txtPlaca, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(PanelVehiculoLayout.createSequentialGroup()
                                        .addComponent(txtMarca, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE))))))
                    .addGroup(PanelVehiculoLayout.createSequentialGroup()
                        .addGap(111, 111, 111)
                        .addComponent(btnCrearVehiculo, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        PanelVehiculoLayout.setVerticalGroup(
            PanelVehiculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelVehiculoLayout.createSequentialGroup()
                .addGap(0, 17, Short.MAX_VALUE)
                .addGroup(PanelVehiculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCEDULA, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCedula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(PanelVehiculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPlaca)
                    .addComponent(txtPlaca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(PanelVehiculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblMarca)
                    .addComponent(txtMarca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(PanelVehiculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblModelo)
                    .addComponent(txtModelo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addComponent(btnCrearVehiculo)
                .addGap(20, 20, 20))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(PanelVehiculo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(PanelVehiculo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCrearVehiculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearVehiculoActionPerformed

        if (txtCedula.getText().isEmpty() || txtMarca.getText().isEmpty() || txtModelo.getText().isEmpty() || txtPlaca.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Llene todos los campos");
        } else {

            Cliente cliente = controladorCliente.buscarCliente(txtCedula.getText());
            if (cliente == null) {
                int desicion = JOptionPane.showConfirmDialog(this, "Este cliente no existe, Desea crear uno nuevo?");
                this.dispose();
                if (desicion == JOptionPane.YES_OPTION) {
                    ventanaPrincipal.getDesktopPane().add(ventanaCliente);
                    ventanaCliente.setVisible(true);
                    ventanaCliente.getTxtCedula().setText(txtCedula.getText());
                    ventanaCliente.getTxtCedula().setEnabled(false);
                } else if (desicion == JOptionPane.NO_OPTION || desicion == JOptionPane.CANCEL_OPTION) {
                    Limpiar();

                }

            } else {

                Vehiculo vehiculo = new Vehiculo(txtPlaca.getText(), txtMarca.getText(), txtModelo.getText(), cliente);
                controladorVehiculo.crearVehiculo(vehiculo);
                cliente.agregarVehiculo(vehiculo);

                JOptionPane.showMessageDialog(this, "Vehiculo registrado correctamente");
                Limpiar();
                this.dispose();
            }

        }

    }//GEN-LAST:event_btnCrearVehiculoActionPerformed

    public JTextField getTxtCedula() {
        return txtCedula;
    }

    public void Limpiar() {
        txtPlaca.setText("");
        txtMarca.setText("");
        txtModelo.setText("");

    }

    public JFormattedTextField getTxtPlaca() {
        return txtPlaca;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PanelVehiculo;
    private javax.swing.JButton btnCrearVehiculo;
    private javax.swing.JLabel lblCEDULA;
    private javax.swing.JLabel lblMarca;
    private javax.swing.JLabel lblModelo;
    private javax.swing.JLabel lblPlaca;
    private javax.swing.JTextField txtCedula;
    private javax.swing.JTextField txtMarca;
    private javax.swing.JTextField txtModelo;
    private javax.swing.JFormattedTextField txtPlaca;
    // End of variables declaration//GEN-END:variables

    public ControladorVehiculo getControladorVehiculo() {
        return controladorVehiculo;
    }

    public ControladorCliente getControladorCliente() {
        return controladorCliente;
    }

    public VentanaCliente getVentanaCliente() {
        return ventanaCliente;
    }

    public VentanaPrincipal getVentanaPrincipal() {
        return ventanaPrincipal;
    }

    public JPanel getPanelVehiculo() {
        return PanelVehiculo;
    }

    public JButton getBtnCrearVehiculo() {
        return btnCrearVehiculo;
    }

    public JLabel getLblCEDULA() {
        return lblCEDULA;
    }

    public JLabel getLblMarca() {
        return lblMarca;
    }

    public JLabel getLblModelo() {
        return lblModelo;
    }

    public JLabel getLblPlaca() {
        return lblPlaca;
    }

    public JTextField getTxtMarca() {
        return txtMarca;
    }

    public JTextField getTxtModelo() {
        return txtModelo;
    }


}
