/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ec.edu.ups.vista;

import ec.edu.ups.controlador.ControladorCliente;
import ec.edu.ups.controlador.ControladorTicket;
import ec.edu.ups.controlador.ControladorVehiculo;
import ec.edu.ups.dao.ClienteDao;
import ec.edu.ups.dao.TicketDao;
import ec.edu.ups.dao.VehiculoDao;
import java.text.ParseException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JDesktopPane;

/**
 *
 * @author paul_
 */
public class VentanaPrincipal extends javax.swing.JFrame {

    private VentanaVehiculo ventanaVehiculo;
    private VentanaCliente ventanaCliente;
    private VentanaIngresoTicket ventanaIngresoTicket;
    private VentanaSalida ventanaSalida;
    private VentanaListar ventanaListar;

    private ClienteDao clienteDAO;
    private VehiculoDao vehiculoDAO;
    private TicketDao ticketDAO;

    private ControladorCliente controladorCliente;
    private ControladorVehiculo controladorVehiculo;
    private ControladorTicket controladorTicket;

    /**
     * Creates new form VentanaPrincipal
     */
    public VentanaPrincipal() throws ParseException {
        initComponents();
        this.setExtendedState(MAXIMIZED_BOTH);
        clienteDAO = new ClienteDao();
        vehiculoDAO = new VehiculoDao();
        ticketDAO = new TicketDao();

        controladorCliente = new ControladorCliente(clienteDAO, vehiculoDAO);
        controladorVehiculo = new ControladorVehiculo(vehiculoDAO);
        controladorTicket = new ControladorTicket(ticketDAO);

        ventanaVehiculo = new VentanaVehiculo(controladorVehiculo, controladorCliente, this);
        ventanaCliente = new VentanaCliente(controladorCliente, this, ventanaVehiculo);
        ventanaIngresoTicket = new VentanaIngresoTicket(controladorCliente, controladorTicket, controladorVehiculo, this);
        ventanaSalida = new VentanaSalida(controladorCliente, controladorTicket, controladorVehiculo);
        ventanaListar = new VentanaListar(controladorTicket);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu4 = new javax.swing.JMenu();
        jMenu5 = new javax.swing.JMenu();
        desktopPane = new javax.swing.JDesktopPane();
        menuBar = new javax.swing.JMenuBar();
        btnRegistroVehiculo = new javax.swing.JMenu();
        btnIngresar = new javax.swing.JMenuItem();
        btnRegistrarVehiculo = new javax.swing.JMenuItem();
        btnIngresoTicket = new javax.swing.JMenuItem();
        btnSalidaTicket = new javax.swing.JMenuItem();
        btnListaTickets = new javax.swing.JMenuItem();
        btnSalir = new javax.swing.JMenuItem();
        btnIdioma = new javax.swing.JMenu();
        btnESP = new javax.swing.JMenuItem();
        btnENG = new javax.swing.JMenuItem();

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        jMenu3.setText("jMenu3");

        jMenu4.setText("File");
        jMenuBar2.add(jMenu4);

        jMenu5.setText("Edit");
        jMenuBar2.add(jMenu5);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.GridLayout(1, 0));
        getContentPane().add(desktopPane);

        btnRegistroVehiculo.setMnemonic('f');
        btnRegistroVehiculo.setText("Menu");

        btnIngresar.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_I, java.awt.event.InputEvent.CTRL_MASK));
        btnIngresar.setMnemonic('o');
        btnIngresar.setText("Registro Cliente");
        btnIngresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIngresarActionPerformed(evt);
            }
        });
        btnRegistroVehiculo.add(btnIngresar);

        btnRegistrarVehiculo.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_R, java.awt.event.InputEvent.CTRL_MASK));
        btnRegistrarVehiculo.setText("Registro Vehiculo");
        btnRegistrarVehiculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarVehiculoActionPerformed(evt);
            }
        });
        btnRegistroVehiculo.add(btnRegistrarVehiculo);

        btnIngresoTicket.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_T, java.awt.event.InputEvent.CTRL_MASK));
        btnIngresoTicket.setMnemonic('s');
        btnIngresoTicket.setText("Ingresar Vehiculo");
        btnIngresoTicket.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIngresoTicketActionPerformed(evt);
            }
        });
        btnRegistroVehiculo.add(btnIngresoTicket);

        btnSalidaTicket.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_MASK));
        btnSalidaTicket.setText("Retirar Vehiculo");
        btnSalidaTicket.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalidaTicketActionPerformed(evt);
            }
        });
        btnRegistroVehiculo.add(btnSalidaTicket);

        btnListaTickets.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_L, java.awt.event.InputEvent.CTRL_MASK));
        btnListaTickets.setMnemonic('a');
        btnListaTickets.setText("Lista de Ticktes");
        btnListaTickets.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListaTicketsActionPerformed(evt);
            }
        });
        btnRegistroVehiculo.add(btnListaTickets);

        btnSalir.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_Q, java.awt.event.InputEvent.CTRL_MASK));
        btnSalir.setMnemonic('x');
        btnSalir.setText("Salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });
        btnRegistroVehiculo.add(btnSalir);

        menuBar.add(btnRegistroVehiculo);

        btnIdioma.setText("Idioma");

        btnESP.setText("Español");
        btnESP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnESPActionPerformed(evt);
            }
        });
        btnIdioma.add(btnESP);

        btnENG.setText("Ingles");
        btnIdioma.add(btnENG);

        menuBar.add(btnIdioma);

        setJMenuBar(menuBar);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btnSalirActionPerformed

    private void btnIngresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIngresarActionPerformed

        desktopPane.add(ventanaCliente);

        ventanaCliente.setVisible(true);
        ventanaIngresoTicket.setVisible(false);
         ventanaSalida.setVisible(false);
        


    }//GEN-LAST:event_btnIngresarActionPerformed

    private void btnIngresoTicketActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIngresoTicketActionPerformed
        desktopPane.add(ventanaIngresoTicket);
        ventanaIngresoTicket.setVisible(true);
ventanaSalida.setVisible(false);
    }//GEN-LAST:event_btnIngresoTicketActionPerformed

    private void btnSalidaTicketActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalidaTicketActionPerformed
        desktopPane.add(ventanaSalida);
        ventanaSalida.setVisible(true);
         ventanaIngresoTicket.setVisible(false);

    }//GEN-LAST:event_btnSalidaTicketActionPerformed

    private void btnRegistrarVehiculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarVehiculoActionPerformed
        desktopPane.add(ventanaVehiculo);
        ventanaVehiculo.setVisible(true);
         ventanaIngresoTicket.setVisible(false);
         ventanaSalida.setVisible(false);
    }//GEN-LAST:event_btnRegistrarVehiculoActionPerformed

    private void btnListaTicketsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListaTicketsActionPerformed
   desktopPane.add(ventanaListar);
   ventanaListar.setVisible(true);
    }//GEN-LAST:event_btnListaTicketsActionPerformed

    private void btnESPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnESPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnESPActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new VentanaPrincipal().setVisible(true);
                } catch (ParseException ex) {
                    Logger.getLogger(VentanaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    public JDesktopPane getDesktopPane() {
        return desktopPane;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem btnENG;
    private javax.swing.JMenuItem btnESP;
    private javax.swing.JMenu btnIdioma;
    private javax.swing.JMenuItem btnIngresar;
    private javax.swing.JMenuItem btnIngresoTicket;
    private javax.swing.JMenuItem btnListaTickets;
    private javax.swing.JMenuItem btnRegistrarVehiculo;
    private javax.swing.JMenu btnRegistroVehiculo;
    private javax.swing.JMenuItem btnSalidaTicket;
    private javax.swing.JMenuItem btnSalir;
    private javax.swing.JDesktopPane desktopPane;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuBar menuBar;
    // End of variables declaration//GEN-END:variables

}
