/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ec.edu.ups.vista;

import ec.edu.ups.controlador.ControladorCliente;
import ec.edu.ups.controlador.ControladorTicket;
import ec.edu.ups.controlador.ControladorVehiculo;
import ec.edu.ups.modelo.Ticket;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author paul_
 */
public class VentanaSalida extends javax.swing.JInternalFrame {

    private Ticket ticket;
    private double fraccion;
    private double total;
    private ControladorCliente controladorCliente;
    private ControladorTicket controladorTicket;
    private ControladorVehiculo controladorVehiculo;
    private Date fechaActual;

    public VentanaSalida(ControladorCliente controladorCliente, ControladorTicket controladorTicket, ControladorVehiculo controladorVehiculo) throws ParseException {
        initComponents();
        this.controladorCliente = controladorCliente;
        this.controladorTicket = controladorTicket;
        this.controladorVehiculo = controladorVehiculo;
        Calendar cal = Calendar.getInstance();
        fechaActual = cal.getTime();
    

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelSalida = new javax.swing.JPanel();
        lblCodigoSalida = new javax.swing.JLabel();
        txtCodigoSalida = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblSalida = new javax.swing.JTable();
        btnSacarVehiculo = new javax.swing.JButton();
        btnSALIR = new javax.swing.JButton();

        PanelSalida.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Salida del Vehiculo", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Tahoma", 0, 18))); // NOI18N

        lblCodigoSalida.setText("CODIGO:");

        tblSalida.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Numero", "Fecha de Ingreso", "Fecha de Salida", "Cedula", "Nombre", "Direccion", "Telefono", "Marca", "Placa", "Modelo", "Fraccion", "Total"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Object.class, java.lang.Object.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Double.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblSalida);

        btnSacarVehiculo.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        btnSacarVehiculo.setText("Retirar Vehiculo");
        btnSacarVehiculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSacarVehiculoActionPerformed(evt);
            }
        });

        btnSALIR.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnSALIR.setText("SALIR");
        btnSALIR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSALIRActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelSalidaLayout = new javax.swing.GroupLayout(PanelSalida);
        PanelSalida.setLayout(PanelSalidaLayout);
        PanelSalidaLayout.setHorizontalGroup(
            PanelSalidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelSalidaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelSalidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelSalidaLayout.createSequentialGroup()
                        .addComponent(lblCodigoSalida)
                        .addGap(18, 18, 18)
                        .addComponent(txtCodigoSalida, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnSacarVehiculo)
                        .addGap(18, 18, 18)
                        .addComponent(btnSALIR, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1252, Short.MAX_VALUE))
                .addContainerGap())
        );
        PanelSalidaLayout.setVerticalGroup(
            PanelSalidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelSalidaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelSalidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(PanelSalidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblCodigoSalida)
                        .addComponent(txtCodigoSalida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnSacarVehiculo))
                    .addGroup(PanelSalidaLayout.createSequentialGroup()
                        .addComponent(btnSALIR, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(1, 1, 1)))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(PanelSalida, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(PanelSalida, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
 public void cargartblSalida() {
        DefaultTableModel modelo = (DefaultTableModel) tblSalida.getModel();
        modelo.setRowCount(0);

        for (Ticket ticket : controladorTicket.ListarTickets()) {
            if (ticket.isEstado() == false) {
                Object[] rowData = {ticket.getNumero(),
                    ticket.getFechaHoraIngreso(),
                    ticket.getFechaHoraSalida(),
                    ticket.getVehiculo().getCliente().getCedula(),
                    ticket.getVehiculo().getCliente().getNombre(),
                    ticket.getVehiculo().getCliente().getDireccion(),
                    ticket.getVehiculo().getCliente().getTelefono(),
                    ticket.getVehiculo().getMarca(),
                    ticket.getVehiculo().getPlaca(),
                    ticket.getVehiculo().getModelo(),
                    ticket.getFraccion(),
                    "$ " + ticket.getTotal()
                };
                modelo.addRow(rowData);
                tblSalida.setModel(modelo);
            }
        }
    }
    private void btnSacarVehiculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSacarVehiculoActionPerformed

        if (txtCodigoSalida.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "El campo no puede estar vacio");

        } else {
            ticket = controladorTicket.buscarTicket(Integer.parseInt(txtCodigoSalida.getText()));
            Ticket t = new Ticket();
            if (ticket == null) {
                JOptionPane.showMessageDialog(this, "El ticket no esta registrado");
            } else {
                
                calcularValor();
                controladorTicket.actualizarTicket(ticket.getNumero(), ticket.getFechaHoraIngreso(), fechaActual, total, ticket.getVehiculo(), false,fraccion);
                JOptionPane.showMessageDialog(this, "El valor a pagar es: " + total);
                cargartblSalida();
                Limpiar();
               

            }

        }

    }//GEN-LAST:event_btnSacarVehiculoActionPerformed

    private void btnSALIRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSALIRActionPerformed
      this.dispose();
    }//GEN-LAST:event_btnSALIRActionPerformed
    public void Limpiar() {
        txtCodigoSalida.setText("");
    }
    //GET TIME RECIBE TIEMPO EN ms 

    public void calcularValor() {
        double minutos =  (fechaActual.getTime() - ticket.getFechaHoraIngreso().getTime()) / 60000;
        fraccion = minutos / 10;
        total = minutos * 0.25;

    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PanelSalida;
    private javax.swing.JButton btnSALIR;
    private javax.swing.JButton btnSacarVehiculo;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblCodigoSalida;
    private javax.swing.JTable tblSalida;
    private javax.swing.JTextField txtCodigoSalida;
    // End of variables declaration//GEN-END:variables

    public Ticket getTicket() {
        return ticket;
    }

    public double getFraccion() {
        return fraccion;
    }

    public double getTotal() {
        return total;
    }

    public ControladorCliente getControladorCliente() {
        return controladorCliente;
    }

    public ControladorTicket getControladorTicket() {
        return controladorTicket;
    }

    public ControladorVehiculo getControladorVehiculo() {
        return controladorVehiculo;
    }

    public Date getFechaActual() {
        return fechaActual;
    }

    public JPanel getPanelSalida() {
        return PanelSalida;
    }

    public JButton getBtnSacarVehiculo() {
        return btnSacarVehiculo;
    }

    public JButton getBtnSALIR() {
        return btnSALIR;
    }

    public JScrollPane getjScrollPane1() {
        return jScrollPane1;
    }

    public JLabel getLblCodigoSalida() {
        return lblCodigoSalida;
    }

    public JTable getTblSalida() {
        return tblSalida;
    }

    public JTextField getTxtCodigoSalida() {
        return txtCodigoSalida;
    }


}
