/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ec.edu.ups.vista;

import ec.edu.ups.controlador.ControladorCliente;
import ec.edu.ups.controlador.ControladorTicket;
import ec.edu.ups.controlador.ControladorVehiculo;
import ec.edu.ups.dao.ClienteDao;
import ec.edu.ups.dao.TicketDao;
import ec.edu.ups.dao.VehiculoDao;
import javax.swing.JDesktopPane;

/**
 *
 * @author paul_
 */
public class VentanaPrincipal extends javax.swing.JFrame {

    
    private VentanaVehiculo ventanaVehiculo;
    private VentanaCliente ventanaCliente;
    private VentanaIngresoTicket ventanaIngresoTicket;
    private VentanaSalida ventanaSalida;
    private VentanaListar ventanaListar;
    
    
    private  ClienteDao clienteDAO;
    private  VehiculoDao vehiculoDAO;
    private  TicketDao ticketDAO;
    
    private ControladorCliente controladorCliente;
    private ControladorVehiculo controladorVehiculo;
    private ControladorTicket controladorTicket;
    
    /**
     * Creates new form VentanaPrincipal
     */
    public VentanaPrincipal() {
        
        clienteDAO = new ClienteDao();
        vehiculoDAO = new VehiculoDao();
        ticketDAO = new TicketDao();
        
        controladorCliente = new ControladorCliente(clienteDAO,vehiculoDAO);
        controladorVehiculo = new ControladorVehiculo(vehiculoDAO);
        controladorTicket = new ControladorTicket(ticketDAO);
        
        ventanaVehiculo = new VentanaVehiculo (controladorVehiculo,controladorCliente);
        ventanaCliente = new VentanaCliente(controladorCliente,this, ventanaVehiculo);
        ventanaIngresoTicket = new VentanaIngresoTicket();
        ventanaSalida = new VentanaSalida();
        ventanaListar = new VentanaListar();
        
        
        
        
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu4 = new javax.swing.JMenu();
        jMenu5 = new javax.swing.JMenu();
        desktopPane = new javax.swing.JDesktopPane();
        menuBar = new javax.swing.JMenuBar();
        btnMenu = new javax.swing.JMenu();
        btnIngresar = new javax.swing.JMenuItem();
        btnIngresoTicket = new javax.swing.JMenuItem();
        btnSalidaTicket = new javax.swing.JMenuItem();
        btnListaTickets = new javax.swing.JMenuItem();
        btnSalir = new javax.swing.JMenuItem();
        btnEdit = new javax.swing.JMenu();
        cutMenuItem = new javax.swing.JMenuItem();
        copyMenuItem = new javax.swing.JMenuItem();
        pasteMenuItem = new javax.swing.JMenuItem();
        deleteMenuItem = new javax.swing.JMenuItem();
        btnIdioma = new javax.swing.JMenu();

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        jMenu3.setText("jMenu3");

        jMenu4.setText("File");
        jMenuBar2.add(jMenu4);

        jMenu5.setText("Edit");
        jMenuBar2.add(jMenu5);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnMenu.setMnemonic('f');
        btnMenu.setText("Menu");

        btnIngresar.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_I, java.awt.event.InputEvent.CTRL_MASK));
        btnIngresar.setMnemonic('o');
        btnIngresar.setText("Ingreso Vehiculo");
        btnIngresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIngresarActionPerformed(evt);
            }
        });
        btnMenu.add(btnIngresar);

        btnIngresoTicket.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_T, java.awt.event.InputEvent.CTRL_MASK));
        btnIngresoTicket.setMnemonic('s');
        btnIngresoTicket.setText("Ingreso Ticket");
        btnIngresoTicket.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIngresoTicketActionPerformed(evt);
            }
        });
        btnMenu.add(btnIngresoTicket);

        btnSalidaTicket.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_MASK));
        btnSalidaTicket.setText("Salida Ticket");
        btnSalidaTicket.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalidaTicketActionPerformed(evt);
            }
        });
        btnMenu.add(btnSalidaTicket);

        btnListaTickets.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_L, java.awt.event.InputEvent.CTRL_MASK));
        btnListaTickets.setMnemonic('a');
        btnListaTickets.setText("Lista de Ticktes");
        btnListaTickets.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListaTicketsActionPerformed(evt);
            }
        });
        btnMenu.add(btnListaTickets);

        btnSalir.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_Q, java.awt.event.InputEvent.CTRL_MASK));
        btnSalir.setMnemonic('x');
        btnSalir.setText("Salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });
        btnMenu.add(btnSalir);

        menuBar.add(btnMenu);

        btnEdit.setMnemonic('e');
        btnEdit.setText("Editar");

        cutMenuItem.setMnemonic('t');
        cutMenuItem.setText("Cut");
        btnEdit.add(cutMenuItem);

        copyMenuItem.setMnemonic('y');
        copyMenuItem.setText("Copy");
        btnEdit.add(copyMenuItem);

        pasteMenuItem.setMnemonic('p');
        pasteMenuItem.setText("Paste");
        btnEdit.add(pasteMenuItem);

        deleteMenuItem.setMnemonic('d');
        deleteMenuItem.setText("Delete");
        btnEdit.add(deleteMenuItem);

        menuBar.add(btnEdit);

        btnIdioma.setText("Idioma");
        menuBar.add(btnIdioma);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(desktopPane, javax.swing.GroupLayout.PREFERRED_SIZE, 621, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(desktopPane, javax.swing.GroupLayout.PREFERRED_SIZE, 398, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btnSalirActionPerformed

    private void btnIngresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIngresarActionPerformed
       // desktopPane.add(ventanaVehiculo);
        desktopPane.add(ventanaCliente);
       // ventanaVehiculo.setVisible(true);
        ventanaCliente.setVisible(true);
        
    }//GEN-LAST:event_btnIngresarActionPerformed

    private void btnIngresoTicketActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIngresoTicketActionPerformed
        desktopPane.add(ventanaIngresoTicket);
        ventanaIngresoTicket.setVisible(true);
        
    }//GEN-LAST:event_btnIngresoTicketActionPerformed

    private void btnSalidaTicketActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalidaTicketActionPerformed
        desktopPane.add(ventanaSalida);
        ventanaSalida.setVisible(true);
        
    }//GEN-LAST:event_btnSalidaTicketActionPerformed

    private void btnListaTicketsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListaTicketsActionPerformed
        desktopPane.add(ventanaListar);
        ventanaListar.setVisible(true);
        
    }//GEN-LAST:event_btnListaTicketsActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaPrincipal().setVisible(true);
            }
        });
    }

    public JDesktopPane getDesktopPane() {
        return desktopPane;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu btnEdit;
    private javax.swing.JMenu btnIdioma;
    private javax.swing.JMenuItem btnIngresar;
    private javax.swing.JMenuItem btnIngresoTicket;
    private javax.swing.JMenuItem btnListaTickets;
    private javax.swing.JMenu btnMenu;
    private javax.swing.JMenuItem btnSalidaTicket;
    private javax.swing.JMenuItem btnSalir;
    private javax.swing.JMenuItem copyMenuItem;
    private javax.swing.JMenuItem cutMenuItem;
    private javax.swing.JMenuItem deleteMenuItem;
    private javax.swing.JDesktopPane desktopPane;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenuItem pasteMenuItem;
    // End of variables declaration//GEN-END:variables

}
